### ISSUE TITLE
Upgrade Pillow to Latest Available

### ISSUE THREAD

**Issue by zmattingly** [jp00p/AGIMUS#464]
With #463 we've bumped a number of packages but we can't upgrade Pillow past 8.4 yet due to at least one breaking change with `/profile`:

```
app-1  | Traceback (most recent call last):
app-1  | 2024-01-04 15:39:24,898 - None
app-1  |   File "/home/bot/.local/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
app-1  |     ret = await coro(arg)
app-1  |   File "/home/bot/.local/lib/python3.10/site-packages/discord/commands/core.py", line 1002, in _invoke
app-1  |     await self.callback(self.cog, ctx, **kwargs)
app-1  |   File "/bot/cogs/profile.py", line 355, in display
app-1  |     photo_content.thumbnail((263, 200), Image.ANTIALIAS)
app-1  | AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

Need to look into our implementation and see what other dragons be lurking if we want to get the latest version.

**Comment by rahmcoff** [comment]
I’m not seeing that.  At least not with Pillow 8.4.  What version are you on?

**Comment by zmattingly** [comment]
Sorry, should have been more clear, this was very bad phrasing on my part. This does not block #463, the version bumped there is 100% fine.

This was bumping it all the way to their latest release, 10.2.0. Apologies.
